# Generated by Django 2.1.1 on 2018-10-15 17:48

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import gitpm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=128)),
                ('hashID', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('message', models.CharField(max_length=1024)),
                ('modifiedFiles', djongo.models.fields.ArrayModelField(model_container=gitpm.models.ModifiedFiles, model_form_class=gitpm.models.ModifiedFilesForm)),
            ],
            options={
                'db_table': 'Commit',
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'EventLog',
            },
        ),
        migrations.CreateModel(
            name='EventLogFields',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('caseID', models.IntegerField()),
                ('activity', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('commit', models.CharField(max_length=40)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitpm.EventLog')),
            ],
            options={
                'db_table': 'EventLogFields',
            },
        ),
        migrations.CreateModel(
            name='ProcessModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=152)),
                ('tasks', djongo.models.fields.ListField()),
                ('constraints', djongo.models.fields.ArrayModelField(model_container=gitpm.models.ProcessModelFields)),
                ('eventlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitpm.EventLog')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('onwer', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Repository',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='eventlog',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitpm.Repository'),
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitpm.Repository'),
        ),
    ]
